# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [4]:
#Solution
import numpy as np
my_age = 46
rand_num = np.random.randint(10,my_age, (1,my_age)) 
rand_num

array([[44, 34, 31, 36, 41, 36, 23, 26, 44, 36, 27, 30, 13, 28, 41, 44,
        34, 38, 19, 20, 38, 29, 24, 45, 24, 11, 19, 45, 43, 14, 24, 22,
        30, 33, 20, 14, 18, 28, 45, 34, 12, 18, 35, 14, 33, 19]])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [11]:
# Solution
arr1 = np.arange(1,50,2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [12]:
# Solution
arr2 = np.linspace(4,7,27)
arr2

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [26]:
# Solution
rand_mat = np.random.rand(5,4)
rand_mat = np.around(rand_mat, 2)
rand_mat

array([[0.17, 0.56, 0.21, 0.17],
       [0.62, 0.99, 0.83, 0.82],
       [0.62, 0.2 , 0.07, 1.  ],
       [0.92, 0.18, 0.66, 0.78],
       [0.07, 0.9 , 0.3 , 0.83]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [31]:
# Solution
rand_intmat = np.random.randint(5,15, (5,5))
rand_intmat

array([[ 6, 13, 13,  5,  5],
       [ 8, 11,  7, 11,  5],
       [11,  7, 14,  9,  7],
       [10, 13, 12,  6, 10],
       [14,  5, 12,  8, 11]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [38]:
# Solution
rand_zero = np.zeros(np.random.randint(1,20),dtype=int)
print (rand_zero, rand_zero.dtype)

[0 0 0] int32


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [42]:
# Solution
# since the dimensions of the array itself is random,the maximum limit in the range (maximum number of rows / columns ) is assumed to be 100.   
rand_ones = np.ones((np.random.randint(1,100),np.random.randint(1,100)),dtype=float)
print (rand_ones, rand_ones.dtype, rand_ones.shape)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]] float64 (59, 69)


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [50]:
# Solution
matrix1 = np.array([[9,25,50,34,45],
                   [3,34,34,65,2],
                   [5,7,3,76,3],
                   [7,8,6,54,6],
                   [23,12,8,5,8]])
print(matrix1)
print(f'The shape of the matrix is : {matrix1.shape},     with type :  {type(matrix1)},    and the dtype is : {matrix1.dtype}')

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
The shape of the matrix is : (5, 5),     with type :  <class 'numpy.ndarray'>,    and the dtype is : int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [72]:
# Solution - A generic solution for identifying the central element of any matrix is proposed
''' Next step checks if the dimensions (both number of rows and columns) is odd, only then there exists central element'''  
shape = list(matrix1.shape)   # the dimensions of the matrix is captured in the variable 'shape' and is a list of numbers
print('The shape of the given matri is : ',shape)
if shape[0] == shape[1]:    # this checks if the number of rows & columns are equal
    if (shape[0] % 2 == 1) and (shape[1] % 2 == 1):
        center_row_col = int(shape[0]/2)  # the identifies the central element   
        center_element = matrix1[center_row_col,center_row_col]
        print ('The center element is :', center_element)
        
else: 
    print('The given matrix is either not square or has even number of rows and columns')
    


The shape of the given matri is :  [5, 5]
The center element is : 3


#### 10. Print the all the elements of 3rd row of the matrix

In [76]:
# Solution
print(matrix1 [2,:]) # Third row - is index row 2 of the matrix (as the indexing starts at 0) and all columns is : 

[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [77]:
# Solution
print(matrix1 [:,3]) # All rows is : and 4th col of the matrix is indexed as 3rd col in the indexing (as the indexing starts at 0) 


[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [88]:
# Solution
shape1 = matrix1.shape

top_left = matrix1[0,0]
top_right = matrix1[0,shape[1]-1]
bottom_left = matrix1[shape[0]-1,0]
bottom_right = matrix1[shape[0]-1, shape[1]-1]
print(f'''        The top left corner element is    : {top_left}
        The top right corner element is   : {top_right}
        The bottom left corner element is : {bottom_left}
        The bottom right corner element is: {bottom_right}'''
        )

        The top left corner element is    : 9
        The top right corner element is   : 45
        The bottom left corner element is : 23
        The bottom right corner element is: 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [104]:
# Solution 
m1 = matrix1[0:2,2:4]
print ('m1 = \n', m1, '\n')

m2 = matrix1[-2::,0:2]
print ('m2 = \n', m2,'\n')

m3 = matrix1 [2::,2::]
print ('m3 = \n', m3)

m1 = 
 [[50 34]
 [34 65]] 

m2 = 
 [[ 7  8]
 [23 12]] 

m3 = 
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [118]:
# Solution
''' np.size() determines the total  number  of elements in the given matrix 
hence the number of columns in new 1 dimensional vector, this becomes the general solutions hence the usage'''

m1_as_rowvector = m1.reshape(1,np.size(m1)) 
print('m1 matrix as row vector : ', m1_as_rowvector)

m2_as_rowvector = m2.reshape(1,np.size(m2)) 
print('m2 matrix as row vector : ', m2_as_rowvector)


m3_as_rowvector = m3.reshape(1,np.size(m3)) 
print('m3 matrix as row vector : ', m3_as_rowvector)


m1 matrix as row vector :  [[50 34 34 65]]
m2 matrix as row vector :  [[ 7  8 23 12]]
m3 matrix as row vector :  [[ 3 76  3  6 54  6  8  5  8]]


# 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [123]:
# Solution
m1m2_row_wise = np.concatenate((m1,m2),axis = 0) # axis = 0 ensures concatenating m2 below m1 
m1m2_col_wise = np.concatenate((m1,m2),axis = 1) # axis = 1 ensures concatenating m2 to the right of m1 
print ('Concatenating with Axis = 0, matrices stacked one below the other - means No change in number of colums: \n', m1m2_row_wise) 
print ('Concatenating with Axis = 1, matrices stacked one after the other to the right - means No change in number of rows: \n', m1m2_col_wise)

Concatenating with Axis = 0, matrices stacked one below the other - means No change in number of colums: 
 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
Concatenating with Axis = 1, matrices stacked one after the other to the right - means No change in number of rows: 
 [[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [136]:
# Solution
add_m1_m2 = m1 + m2
sub_m1_m2 = m1 - m2
mul_m1_m2 = m1 * m2  # this is element to element multiplication and is NOT matrix multiplication
div_m1_m2 = m1 / m2

print(f'''Addition of m1 & m2 is : \n{add_m1_m2}
\nSubtraction of m1 & m2 is : \n {sub_m1_m2}
\nMultiplication of m1 & m2 is :\n {mul_m1_m2}
\nDivision of m1 & m2 is : \n {div_m1_m2}
            ''') 


Addition of m1 & m2 is : 
[[57 42]
 [57 77]]

Subtraction of m1 & m2 is : 
 [[43 26]
 [11 53]]

Multiplication of m1 & m2 is :
 [[350 272]
 [782 780]]

Division of m1 & m2 is : 
 [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]
            


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [153]:
# Solution
import numpy as np
m3_extract = np.delete(m3, 0, 0)  # deleting the first row of m3
m3_extract = np.delete(m3_extract, 2,1)    # deleting the last column
m2_m3extract = m2 + m3_extract
print('The sum of m2 and selected portion of m3 (after deleting first row and last column is :\n', m2_m3extract)

The sum of m2 and selected portion of m3 (after deleting first row and last column is :
 [[13 62]
 [31 17]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [169]:
# Solution
import numpy as np
me1 = m1.mean(axis = 1)
me1 = me1.reshape(1,2)
m4 = np.concatenate((m1,me1),axis=0)
print(f'The concatenated matrix of m1 with mean of the m1 (column wise) is :\n',m4)


The concatenated matrix of m1 with mean of the m1 (column wise) is :
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [171]:
# Solution
mat_prod = np.matmul(m3, m4)
print(f' The matrix multiplication between, m3 and m4 is :\n',mat_prod)

 The matrix multiplication between, m3 and m4 is :
 [[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [198]:
# Solution
matrix1 = np.array([[9,25,50,34,45],
                   [3,34,34,65,2],
                   [5,7,3,76,3],
                   [7,8,6,54,6],
                   [23,12,8,5,8]])

# row wise mean and minimum & maximum of row wise mean of the given matrix
matrix1_row_mean = matrix1.mean(axis = 1)
#print(f'The row wise mean of the given matrix is :', matrix1_row_mean)
row_mean_max = round(max(matrix1_row_mean),2)
row_mean_min = round(min(matrix1_row_mean),2)
print(f'\nThe maximum of row wise mean of the given matrix is :', row_mean_max)
print(f'The minimum of row wise mean of the given matrix is :', row_mean_min)

# row wise variance and minimum & maximum of row wise variance of the given matrix
matrix1_row_var = matrix1.var(axis = 1)
#print(f'\n\nThe row wise variance of the given matrix is :', matrix1_row_var)
row_var_max = round(max(matrix1_row_var),2)
row_var_min = round(min(matrix1_row_var),2)
print(f'\n\nThe maximum of row wise variance of the given matrix is :', row_var_max)
print(f'The minimum of row wise variance of the given matrix is :', row_var_min)

# row wise standard deviation and minimum & maximum of row wise standard deviation of the given matrix
matrix1_row_std = (matrix1.std(axis = 1))
#print(f'\n\nThe row wise standard deviation of the given matrix is :', matrix1_row_std)
row_std_max = round(max(matrix1_row_std),2)
row_std_min = round(min(matrix1_row_std),2)
print(f'\n\nThe maximum of row wise standard deviation of the given matrix is :', row_std_max)
print(f'The minimum of row wise standard deviation of the given matrix is :', row_std_min)


The maximum of row wise mean of the given matrix is : 32.6
The minimum of row wise mean of the given matrix is : 11.2


The maximum of row wise variance of the given matrix is : 820.16
The minimum of row wise variance of the given matrix is : 39.76


The maximum of row wise standard deviation of the given matrix is : 28.64
The minimum of row wise standard deviation of the given matrix is : 6.31


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [246]:
# Solution 
import numpy as np

runs = np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls_faced = np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])

# Average runs scored sorted in descending order
avg = runs.mean(axis=1)  # mean runs scored for each player
avg_sorted = np.sort(avg) # sorting the runs in ascending order
reverse_avg_sort  = avg_sorted[::-1]  # sorting in descending order
print(("Average Run Rate, in descending order : ",reverse_avg_sort)

sr = runs.sum(axis=1)*100/balls_faced.sum(axis=1)   # mean strike rate scored for each player
sr_sort = np.sort(sr)                               # sorting the runs in ascending order
reverse_sr_sort = np.around(sr_sort[::-1],2)        # sorting in descending order
print("Strike rate, in descending order : ", reverse_sr_sort)

[53.5  51.5  47.25 29.   13.25]
Strike rate in descending order :  [161.11 101.42  98.44  94.93  49.53]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [269]:
# Solution

marks = np.array([65,84,47,56,89,98,48,77,80,39])
#print(marks.shape)
marks = marks.reshape(len(marks),1) # converted into an arry of n (rows) x 1 (col)
num_of_candidates = len(marks)      # number of candidates
print('Total number of candidates   :',num_of_candidates)

cutt_off = 50
bool_marks = marks>=50       # check the elements that are greater than or equal to 50 and stores the truth value in variable bool_marks
passed = bool_marks.sum(axis=0) # collects the number of candidates with truth value 'True', hence number of passed
print('Number of candidates passed : ', passed)
print('Number of candidates failed : ', len(marks)-passed)



Total number of candidates   : 10
Number of candidates passed :  [7]
Number of candidates failed :  [3]


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [28]:
# Solution
import numpy as np
marks = np.array([65,84,47,56,89,98,48,77,80,39])
number_of_passed = (marks>=50)  # returns a boolean array with 'true' if condition is fulfilled else returns 'false
originally_passed = np.sum(number_of_passed)  # sums all the truth vlaues (boolean values) as 1 if true and 0 if false


modified_marks = marks
count = 0
for mark in modified_marks:
    if (mark>=44) and (mark<=49):
        modified_marks[count] = mark + 5     # awarding mercy marks for students scoring marks between 45 and 49 (both 45 & 49 included)
    
    elif (modified_marks[count]>80):
        modified_marks[count] = mark + 56    # awarding "bonus" marks (5 marks) for students scoring marks above 80 (strictly greater than 80)
    
    if (modified_marks[count]>100):
        modified_marks[count] = 100          # Limiting the maximum marks to 100 after award of bonus marks 
        
    count = count+1

# assuming the pass mark as 50

num_of_passed_modified = (modified_marks>=50)  # returns a boolean array with 'true' if condition is fulfilled else returns 'false'
modified_passes = np.sum(num_of_passed_modified) # sums all the truth vlaues (boolean values) as 1 if true and 0 if false
increase_in_passes =  (modified_passes - originally_passed)
percentage_increase = np.around((increase_in_passes*100/originally_passed),2)
print(f'The increase in pass percentage is : {percentage_increase} %')


The increase in pass percentage is : 28.57 %


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [306]:
# Solution

x = np.arange(1.,60001.) # converted to float 
y = np.arange(1.,60001.) # converted to float
z = ((x**2)+8)/y
print("The calculuation yields an array : \n", z)


The calculuation yields an array : 
 [9.00000000e+00 6.00000000e+00 5.66666667e+00 ... 5.99980001e+04
 5.99990001e+04 6.00000001e+04]


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
#The Github account has been created this solution has been uploaded.
# A short writeup on Numpy is aslo uploaded as a separate PDF file.
# The git hub repository details are as under to access the above submittals: 
# https://github.com/arunkvee/Python_for_DS.git

